// Skill names enum
export const SkillNames = {
  JS: "js",
  HTML: "html",
  CSS: "css",
  REACT: "react",
  TAILWIND: "tailwind",
  JAVA: "java",
  SPRING: "spring",
  POSTGRES: "postgres",
  MYSQL: "mysql",
  GIT: "git",
  GITHUB: "github",
  AWS: "aws",
  CLOUDFLARE: "cloudflare",
  AZURE: "azure",
  HIBERNATE: "hibernate",
  JSP: "jsp",
  SERVLETS: "servlets",
  JDBC: "jdbc",
  SHOPIFY: "shopify",
  LIQUID: "liquid",
};

export const SKILLS = {
  js: {
    id: 1,
    name: "js",
    label: "JavaScript",
    shortDescription: "A scripting language used to make web pages interactive and dynamic.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
  },
  html: {
    id: 2,
    name: "html",
    label: "HTML5",
    shortDescription: "The standard markup language used to structure content on the web.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
  },
  css: {
    id: 3,
    name: "css",
    label: "CSS3",
    shortDescription: "A style sheet language used to describe the visual presentation of HTML elements.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
  },
  react: {
    id: 4,
    name: "react",
    label: "React JS",
    shortDescription: "A JavaScript library for building fast and reusable user interfaces.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
  },
  tailwind: {
    id: 5,
    name: "tailwind",
    label: "Tailwind CSS",
    shortDescription: "A utility-first CSS framework for rapidly building UI.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
  },
  java: {
    id: 6,
    name: "java",
    label: "Java",
    shortDescription: "A high-level, class-based, object-oriented programming language.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
  },
  spring: {
    id: 7,
    name: "spring",
    label: "Spring Boot",
    shortDescription: "An open-source Java-based framework to create microservices.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  },
  "spring boot": {
    id: 7,
    name: "spring boot",
    label: "Spring Boot",
    shortDescription: "An open-source Java-based framework to create microservices.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  },
  "java spring boot": {
    id: 7,
    name: "java spring boot",
    label: "Java Spring Boot",
    shortDescription: "An open-source Java-based framework to create microservices.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  },
  postgres: {
    id: 8,
    name: "postgres",
    label: "PostgreSQL",
    shortDescription: "A powerful open-source relational database system.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
  },
  mysql: {
    id: 9,
    name: "mysql",
    label: "MySQL",
    shortDescription: "An open-source relational database management system.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
  },
  git: {
    id: 10,
    name: "git",
    label: "Git",
    shortDescription: "A distributed version control system.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
  },
  github: {
    id: 11,
    name: "github",
    label: "GitHub",
    shortDescription: "A platform to host, manage, and collaborate on code.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
  },
  aws: {
    id: 12,
    name: "aws",
    label: "AWS",
    shortDescription: "Amazon Web Services cloud platform.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aws/aws-original.svg",
  },
  azure: {
    id: 13,
    name: "azure",
    label: "Azure",
    shortDescription: "Microsoft Azure cloud computing service.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg",
  },
  hibernate: {
    id: 14,
    name: "hibernate",
    label: "Hibernate",
    shortDescription: "An object-relational mapping tool for the Java programming language.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hibernate/hibernate-original.svg",
  },
  jsp: {
    id: 15,
    name: "jsp",
    label: "JSP",
    shortDescription: "JavaServer Pages is a collection of technologies that helps software developers create dynamically generated web pages.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", // Fallback to Java
  },
  servlets: {
    id: 16,
    name: "servlets",
    label: "Servlets",
    shortDescription: "Java Servlets are programs that run on a Web or Application server.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", // Fallback to Java
  },
  jdbc: {
    id: 17,
    name: "jdbc",
    label: "JDBC",
    shortDescription: "Java Database Connectivity is an API for the Java programming language that defines how a client may access a database.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", // Fallback to Java
  },
  shopify: {
    id: 18,
    name: "shopify",
    label: "Shopify",
    shortDescription: "An e-commerce platform for online stores and retail point-of-sale systems.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/shopify/shopify-original.svg", // Not standard devicon, but might work if available
  },
  liquid: {
    id: 19,
    name: "liquid",
    label: "Liquid",
    shortDescription: "An open-source template language created by Shopify and written in Ruby.",
    color: "#915EFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg", // Fallback
  },
};
